"""update_table_company4

Revision ID: 07eb1dcd159f
Revises: 481b41ab2c31
Create Date: 2025-02-07 14:08:38.645749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07eb1dcd159f'
down_revision: Union[str, None] = '481b41ab2c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structuremembers', sa.Column('structure_id', sa.Integer(), nullable=False))
    op.drop_constraint('structuremembers_structure_name_fkey', 'structuremembers', type_='foreignkey')
    op.create_foreign_key(None, 'structuremembers', 'structures', ['structure_id'], ['id'])
    op.drop_column('structuremembers', 'structure_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structuremembers', sa.Column('structure_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'structuremembers', type_='foreignkey')
    op.create_foreign_key('structuremembers_structure_name_fkey', 'structuremembers', 'structures', ['structure_name'], ['name'])
    op.drop_column('structuremembers', 'structure_id')
    # ### end Alembic commands ###
