"""update_table_relaion2

Revision ID: 0dc4775d46e0
Revises: 12b8979b70f4
Create Date: 2025-02-09 13:14:21.062130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc4775d46e0'
down_revision: Union[str, None] = '12b8979b70f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('newss_author_id_fkey', 'newss', type_='foreignkey')
    op.create_foreign_key(None, 'newss', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'newss', type_='foreignkey')
    op.create_foreign_key('newss_author_id_fkey', 'newss', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###
