"""update_table_relaion

Revision ID: 12b8979b70f4
Revises: 33868870b708
Create Date: 2025-02-08 15:09:30.029710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b8979b70f4'
down_revision: Union[str, None] = '33868870b708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('structuremembers_user_id_fkey', 'structuremembers', type_='foreignkey')
    op.drop_constraint('structuremembers_manager_id_fkey', 'structuremembers', type_='foreignkey')
    op.drop_constraint('structuremembers_structure_id_fkey', 'structuremembers', type_='foreignkey')
    op.create_foreign_key(None, 'structuremembers', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'structuremembers', 'structuremembers', ['manager_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'structuremembers', 'structures', ['structure_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_company_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'companys', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_company_id_fkey', 'users', 'companys', ['company_id'], ['id'])
    op.drop_constraint(None, 'structuremembers', type_='foreignkey')
    op.drop_constraint(None, 'structuremembers', type_='foreignkey')
    op.drop_constraint(None, 'structuremembers', type_='foreignkey')
    op.create_foreign_key('structuremembers_structure_id_fkey', 'structuremembers', 'structures', ['structure_id'], ['id'])
    op.create_foreign_key('structuremembers_manager_id_fkey', 'structuremembers', 'structuremembers', ['manager_id'], ['id'])
    op.create_foreign_key('structuremembers_user_id_fkey', 'structuremembers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
