"""update_table_company3

Revision ID: 481b41ab2c31
Revises: 59e65efd4c53
Create Date: 2025-02-07 14:04:31.123134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481b41ab2c31'
down_revision: Union[str, None] = '59e65efd4c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('companys_structure_id_fkey', 'companys', type_='foreignkey')
    op.drop_column('companys', 'structure_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companys', sa.Column('structure_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('companys_structure_id_fkey', 'companys', 'structures', ['structure_id'], ['id'])
    # ### end Alembic commands ###
