"""update_table_company

Revision ID: 61ffa1104bc7
Revises: b059465b3fa8
Create Date: 2025-02-07 13:20:01.512951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ffa1104bc7'
down_revision: Union[str, None] = 'b059465b3fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companys', sa.Column('structure_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companys', 'structures', ['structure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companys', type_='foreignkey')
    op.drop_column('companys', 'structure_id')
    # ### end Alembic commands ###
