"""update_table_news2

Revision ID: b059465b3fa8
Revises: eb0d8fb87b88
Create Date: 2025-02-07 12:00:01.891992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b059465b3fa8'
down_revision: Union[str, None] = 'eb0d8fb87b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newss', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'newss', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'newss', type_='foreignkey')
    op.drop_column('newss', 'author_id')
    # ### end Alembic commands ###
